/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface WebhookUrlValues {
  /**
   * Webhook URL
   *
   */
  webhookUrl: string;
}

/**
 * Slack Webhook URL
 *
 * @comments Authenticate requests to Slack using a Webhook URL.
 * This object is used to support type hinting.
 */
export const webhookUrl = {
  key: "webhookUrl",
  perform: (_values: WebhookUrlValues): Promise<void> => Promise.resolve(),
  inputs: {
    webhookUrl: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Slack Webhook URL Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const slackWebhookUrl = (
  stableKey: string,
  values: {
    webhookUrl: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "slack",
          true,
          context.componentRegistry
        );
      },
      key: "webhookUrl",
      values,
    },
  });
};
