name: Deploy Prismatic code-native integrations

on:
  push:
    branches:
      - main

jobs:
  build-integrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        integration: [todoist]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if integration needs publishing
        id: integration-filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            integration:
              - "integrations/${{ matrix.integration }}/**"
              - "shared-libs/${{ matrix.integration }}/**"
              - "shared-libs/acme/**"
              - "**"
          # TODO: Remove "**" above and uncomment the line below to only build when relevant files change
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: "24.10.0"
        if: steps.integration-filter.outputs.integration == 'true'
      - name: Install dependencies
        run: npm install
        if: steps.integration-filter.outputs.integration == 'true'
      - name: Build ${{ matrix.integration }} integration
        run: npm run build
        working-directory: ./integrations/${{ matrix.integration }}
        if: steps.integration-filter.outputs.integration == 'true'
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.integration }}-build
          path: ./integrations/${{ matrix.integration }}/dist
        if: steps.integration-filter.outputs.integration == 'true'

  publish-integrations:
    runs-on: ubuntu-latest
    needs: [build-integrations]
    strategy:
      matrix:
        integration: [todoist]
        environment: [australia, canada]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if integration needs publishing
        id: integration-filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            integration:
              - "integrations/${{ matrix.integration }}/**"
              - "shared-libs/${{ matrix.integration }}/**"
              - "shared-libs/acme/**"
              - "**"
          # TODO: Remove "**" above and uncomment the line below to only build when relevant files change
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.integration }}-build
          path: ./integrations/${{ matrix.integration }}/dist
        if: steps.integration-filter.outputs.integration == 'true'
      - name: Publish ${{ matrix.integration }} to ${{ matrix.environment }}
        uses: prismatic-io/integration-publisher@v1.4
        with:
          PATH_TO_CNI: ./integrations/${{ matrix.integration }}
          PRISMATIC_URL: ${{ vars.PRISMATIC_URL }}
          PRISM_REFRESH_TOKEN: ${{ secrets.PRISM_REFRESH_TOKEN }}
          MAKE_AVAILABLE_IN_MARKETPLACE: false
        if: steps.integration-filter.outputs.integration == 'true'
      - name: Note if integration did not need publishing
        run: |
          echo "No changes detected in the ${{ matrix.integration }} integration. Skipping publish step." >> "$GITHUB_STEP_SUMMARY"
        if: steps.integration-filter.outputs.integration == 'false'
