name: Deploy Prismatic low-code integrations

on:
  push:
    branches:
      - main

jobs:
  # Get a list of integrations to deploy
  list-integrations:
    runs-on: ubuntu-latest
    outputs:
      integrations: ${{ steps.list-integrations.outputs.integrations }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: List integrations
        id: list-integrations
        run: |
          integrations=$(ls -d low-code-integrations/*.yml | xargs -n 1 basename | sed -e 's/.yml//' | jq -R -s -c 'split("\n")[:-1]')
          echo "integrations=$integrations" >> "$GITHUB_OUTPUT"

  publish-integrations:
    runs-on: ubuntu-latest
    needs: [list-integrations]
    strategy:
      matrix:
        integration: ${{ fromJson(needs.list-integrations.outputs.integrations) }}
        environment: [australia, canada]
      fail-fast: false
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set integration ID var name
        id: integration_id
        run: |
          echo "integration_id=INTEGRATION_ID_$(echo ${{ matrix.integration }} | tr '[:lower:]' '[:upper:]')" >> $GITHUB_OUTPUT
      - name: Publish ${{ matrix.integration }} to ${{ matrix.environment }}
        uses: prismatic-io/integration-publisher@v1.4
        with:
          PATH_TO_YML: ./low-code-integrations/${{ matrix.integration }}.yml
          PRISMATIC_URL: ${{ vars.PRISMATIC_URL }}
          PRISM_REFRESH_TOKEN: ${{ secrets.PRISM_REFRESH_TOKEN }}
          MAKE_AVAILABLE_IN_MARKETPLACE: false
          INTEGRATION_ID: ${{ vars[steps.integration_id.outputs.integration_id] }}
